### ISSUE TITLE
Can not build project from console 

### ISSUE THREAD

**Issue by vbauer** [nisrulz/easydeviceinfo#12]
I've got the following error during `gradlew build`:
```
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
```

It looks like gradle wrapper jar file was missed in "gradle/wrapper".

**Comment by nisrulz** [comment]
@vbauer yes, i see the issue. I will update the repository with missing jar files.

**Comment by nisrulz** [comment]
@vbauer updated the library code. 

To build it from console and from Android Studio, just have to do one extra step.

Goto `library` module > `build.gradle`.

Comment the below line
`apply from: 'https://raw.github.com/nisrulz/gradle-mvn-push/master/gradle-mvn-push.gradle'`

Thats it. Now you can build the whole project from Android Studio and console.

**Comment by vbauer** [comment]
Thank you for information.
