### ISSUE TITLE
Spelling mistake in one of the battery status methods

### ISSUE THREAD

**Issue by arnabc** [nisrulz/easydeviceinfo#13]
There is a spelling mistake in one of the battery functions in ```EasyBatteryMod```, currently it is named as ```getBatteryTemprature``` which should be ```getBatteryTemperature``` (missing `e` after `temp`).

**Comment by nisrulz** [comment]
Fixed in 7df3e2bfcea6a4b2cb21f482f977952ade97de9d 

The update should be available in few hours without any change required on client side.
