### ISSUE TITLE
App gives carrier info about sim1 only

### ISSUE THREAD

**Issue by vjs3** [nisrulz/easydeviceinfo#16]
My mobile is dual sim, all the features are working fine but it only shows carrier info for sim1 automatically. It would be great if shows the number of sim present and carrier info for each of the available sim.

**Comment by nisrulz** [comment]
@vjs3 thats a nice recommendation. I will update it in the next release. Thanks

**Comment by vjs3** [comment]
Sure! I will also try to make some tweaks and send you a PR for some other features once I got the time.

**Comment by nisrulz** [comment]
Implemented the functionality in commit 4346f9ca233498f912875732ece84c9b683525ba in `develop` branch.

Should test a bit more and would release it in the next version.
