### ISSUE TITLE
Release 2.1.0 not on mavencentral yet....

### ISSUE THREAD

**Issue by sirvon** [nisrulz/easydeviceinfo#17]
The readme states v2.1.0 is available via maven but that's not so....

Thank you for the lib!

**Comment by nisrulz** [comment]
This is weird, I am pretty much sure i published it. It seemed to have vanished. I just checked.

Let me re publish it. Thank you for reporting this.

**Comment by nisrulz** [comment]
I just republished it. Should be available in next 2-3 hours.

Thank you.

**Comment by nisrulz** [comment]
Closing as fixed.
