### ISSUE TITLE
Can't create handler inside thread that has not called Looper.prepare()

### ISSUE THREAD

**Issue by DimaDDM** [nisrulz/easydeviceinfo#22]
In method ` public final String getUA()`

- Android API version < 17 (4.1.2)

- Devices Samsung  GT-N7000, GT-I8190

**Comment by nisrulz** [comment]
Please call `getUA()` from the UI thread only. [[Wiki Link](https://github.com/nisrulz/easydeviceinfo/wiki/Usage#easyidmod)]

Call like below

```java
runOnUiThread (new Thread(new Runnable() { 
         public void run() {
             String ua = easyIdMod.getUA();
         }
     }));
```

**Comment by nisrulz** [comment]
Closing this issue for now. Reopen if this still persists.
