### ISSUE TITLE
Get Android Advertiser ID issue

### ISSUE THREAD

**Issue by trafficteam7** [nisrulz/easydeviceinfo#34]
Hello.
There is a mistake in the next code:
```
easyIdMod.getAndroidAdId(MainActivity.this, new EasyIdMod.AdIdentifierCallback() {
    @Override
    public void onSuccess(String adIdentifier, boolean adDonotTrack) {
        // Do something with the advertiser's ID
    }
});
```
you have **easyIdMod** here, but it doesn't have function **getAndroidAdId**.
Maybe here should be **easyAdsMod**?

**Comment by trafficteam7** [comment]
for me works the next code:
```
easyAdsMod.getAndroidAdId(new EasyAdsMod.AdIdentifierCallback() {
            @Override
            public void onSuccess(String adIdentifier, boolean adDonotTrack) {
                // Do something with the advertiser's ID
                Log.i("Your Ad Id", adIdentifier);
            }
        });
```

**Comment by nisrulz** [comment]
> for me works the next code:
> 
> ```
> easyAdsMod.getAndroidAdId(new EasyAdsMod.AdIdentifierCallback() {
>             @Override
>             public void onSuccess(String adIdentifier, boolean adDonotTrack) {
>                 // Do something with the advertiser's ID
>                 Log.i("Your Ad Id", adIdentifier);
>             }
>         });
> ```

This is correct. The wiki has a mistake. I will update it.

**Comment by nisrulz** [comment]
Updated 🎉 

Thank you for bringing this to my notice.
