### ISSUE TITLE
[Feature Req] Monitor values for change and emit the updated value

### ISSUE THREAD

**Issue by vijayakumarmariyappan** [nisrulz/easydeviceinfo#37]
@nisrulz 

Clarification-will it monitor and give json of each module? It will be good it can deliver device info whenever changes happening. Thank you!

**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
need to call function and get info. but it would be nice if i can info whenever the changes happening.. let us say my device switched from mobile data to wifi , then the library will notify me about that event so that I can update my UI

**If the current behavior is a bug, please provide the steps to reproduce.**

similar to this library
https://github.com/appzy/DeviceInfo

**Comment by nisrulz** [comment]
In the current form, it cannot emit a value when the value changes. This can be a good feature to have though.

Also note EasyDeviceInfo is a bit behind on updates, it has some updates in `develop` branch but thats housekeeping.

**Comment by vijayakumarmariyappan** [comment]
@nisrulz Thanks for your response :) Happy Christmas :)
