### ISSUE TITLE
Add missing zero for device time

### ISSUE THREAD

**Issue by PDDStudio** [nisrulz/easydeviceinfo#6]
Please add the missing zero for the device time.

E.g if it's 04:09:42 o'clock
the method `getFormatedTime()` will return `4:9:42`

It would be better to have it correctly formatted to return `04:09:42`

**Comment by nisrulz** [comment]
updated code in `develop` branch, commit 6e4c8ac810bed1f17572a0cb1630107182e9f0a4 fixes it. Will add it in the next release of the library.

**Comment by PDDStudio** [comment]
Alright great, thanks in advance.
